export enum CONTACT_ACTION  {
     FETCH_CONTACT = 'FETCH_CONTACT',
     ADD_CONTACT = 'ADD_CONTACT',
     EDIT_CONTACT = 'EDIT_CONTACT',
     DELETE_CONTACT = 'DELETE_CONTACT',
     ADD_TO_FAVORITE_CONTACT = 'ADD_TO_FAVORITE_CONTACT',
     REMOVE_FAVORITE_CONTACT = 'REMOVE_FAVORITE_CONTACT',
     SET_LOADING='SET_LOADING'
}